#!/usr/bin/env python3
"""Discovery tool — from a business description to an AI employee candidate.

This is the runnable proof of the FDE (forward-deployed engineering) mindset:
you can take a vague business pain and produce a structured Discovery canvas
plus an AI employee candidate skeleton, without writing any AI code yet.

本工具是可运行的 FDE（前线部署工程）思维证明：你可以把一个模糊的业务痛点，
产出一份结构化的 Discovery 画布加一个 AI 员工候选骨架，而无需先写任何 AI 代码。

Usage · 用法:
    python discover.py --process "采购工程师核查 BOM" --pain "耗时且容易不一致"
    python discover.py --process "..." --pain "..." --json

Dependencies · 依赖: Python 3 standard library only · 仅用 Python 3 标准库。
"""
import argparse
import json
import datetime


def discover(process: str, pain: str) -> str:
    return f"""# Discovery Canvas · 发现画布

**Business process · 业务过程:** {process}
**Pain point · 痛点:** {pain}

## Tasks (decompose the work) · 任务（拆解工作）
1. ...
2. ...
3. ...

## AI Opportunity (what AI can take on) · AI 机会（AI 可承担的部分）
- [ ] Retrieval · 检索
- [ ] Comparison · 比对
- [ ] Rule-based validation · 基于规则的校验
- [ ] Report generation · 报告生成

## AI Employee Candidate · AI 员工候选
**Role · 角色:** ...
**Responsibilities · 职责:**
- ...
**Skills · 技能:**
- ...

---
_Generated by ai-employee-blueprint/discovery · 由 ai-employee-blueprint/discovery 生成 · {datetime.date.today().isoformat()}_
"""


def main():
    ap = argparse.ArgumentParser(
        description="Turn a business description into an AI employee candidate. "
        "把业务描述转化为 AI 员工候选。"
    )
    ap.add_argument("--process", required=True, help="The business process · 业务过程")
    ap.add_argument("--pain", required=True, help="The pain point · 痛点")
    ap.add_argument("--json", action="store_true", help="Emit JSON · 输出 JSON")
    args = ap.parse_args()

    canvas = discover(args.process, args.pain)
    if args.json:
        print(json.dumps(
            {"process": args.process, "pain": args.pain, "canvas": canvas},
            ensure_ascii=False, indent=2,
        ))
    else:
        print(canvas)


if __name__ == "__main__":
    main()
